### ISSUE TITLE
Interaction model builder

### ISSUE THREAD

**Issue by GeoffAtHome** [lordpengwin/muzak#14]
Hi,

I am interested in automatically build the full interaction model. I.e. combining all the speech assets into a single JSON file. I believe this could be useful to automatically configure the players, artists, albums and genres. So far I have a prototype working for artists, albums and genres but needs a lot of manual intervention.

The process is simple. Edit the config.js file. Run the tool that generates the speech.JSON. The tool extracts all the albums, artists etc from your squeezebox server. The speech.JSON is deployed to Alexa and job done. Shame the speech.JSON file cannot be automatically deployed using something like Claudia.

This work also resolve the case sensitive issue with the Squeezebox server.

Reason why I am posting here is two fold. One to let you know what I am doing and secondly to make sure no one else has already done the same thing (that would save me time).

Cheers,
Geoff

**Comment by GeoffAtHome** [comment]
I have completed this work and it works better than the what is here but without what is here I could not have done what I have built.

**Comment by MikeDeSantis** [comment]
I hope to be getting back into this soon, thanks for the work and update @GeoffAtHome!

**Comment by GeoffAtHome** [comment]
Next thing I want to try is to turn Alexa into a Squeezebox. I.e. serve the music directly to Alexa. This should be possible just need to understand how to registered a speakerless Squeezebox.....

**Comment by MikeDeSantis** [comment]
Hello @GeoffAtHome!  Do you have any kind of a procedure written for generating the speech assets from the Squeezebox server?  I'd like to try this out.  Thanks!

**Comment by GeoffAtHome** [comment]
Hi,

 

I do it is checked into GitHub on my branch (if that’s the right term). It enumerate artists, albums and genres. I think it works OK for me. Just built on the other work that has gone before.

 

Cheers,
Geoff

**Comment by MikeDeSantis** [comment]
Great.  Do you have any plans to incorporate that functionality from your branch back into the main trunk?  If so do you have any kind of timeframe?  Thanks again!

**Comment by GeoffAtHome** [comment]
If I knew how to then I would….

**Comment by glacket** [comment]
@GeoffAtHome is your fork working with native playback commands from Amazon, without having to say "Alex, Tell Muzak"? Your intents under your fork look like you got that working.

**Comment by GeoffAtHome** [comment]
As it enumerates all the albums and artist I can say

 

“Play Pink Floyd” or “Play Dark Side Of the Moon” or “Play Dark Side of the moon by Pink Floyd”.

 

What I cannot say is “Alexa ask Muzak to play Pink Floyd”. If I do this my Amazon account plays Pink Floyd. This may be because I have as the invocation name “ask muzak”. I have also set the global fields to for “Audio Player” to yes.

 

I think, if I get round to the next part, which is to use Alexa as a headless Squeezebox, then it may work better with Alexa playing the music. Something to try in the future…..

**Comment by glacket** [comment]
@GeoffAtHome can you specify a player? As in "alexa, play pink Floyd in kitchen" or "alexa, play music in kitchen", "alexa, stop music in kitchen", "alexa, play glackets playlist in kitchen"

**Comment by GeoffAtHome** [comment]
Again, the skill need to be activated before the second command is given. Does “Alexa, play music in the kitchen” work for you?

**Comment by glacket** [comment]
@GeoffAtHome I guess I'm confused. I thought your fork of the skill was activated natively by saying "alexa, play pink Floyd", when your fork is configured as the native music playback in AWS. I have 12 rooms with speakers in the ceiling connected to 12 usb soundcards running on a pc running 12 instances of squeezelite. Currently, I have to say "alexa, open muzak" which will activate the current skill fork. Alexa replies "squeezebox control started". Then I can say "play music in kitchen" "lower volume in kitchen" or "play playlist glacket in kitchen", depending on the name of my audio zone or the name of the artist or name of the playlist squeezebox wont play anything, most of the time everything works though. I was hoping with native playback functionality, I would no longer have to say "alexa, open muzak", or "alexa tell muzal to......." .

**Comment by MikeDeSantis** [comment]
@GeoffAtHome - In README.md, under section "Publish the skill (manual)", is the zip file creation command incomplete for your new speech asset model generation updates?

From: **zip -r muzak.zip muzak.js config.js node_modules**
To:  **zip -r muzak.zip muzak.js config.js _album.js artist.js genre.js_ node_modules**

**Comment by GeoffAtHome** [comment]
@MikeDeSantis  Look in the speechAssets folder. The old format is ALBUM.txt, ARTIST.txt, GENRE.txt, PLAYERS.txt and utterences.txt. The intents are in intents.json. The new format combines these into speechAssets.json. The format is correct but last time I tried using this it failed to build hence creating both versions. 

It is far easier to upload a single file rather that the six individual. I think Amazon are looking for a method to automate the publishing of these files which would be great - maybe this is available now as it has been a while since I have looked into this.

**Comment by MikeDeSantis** [comment]
Thanks @GeoffAtHome, I totally agree with the speechAssets.json consolidation.  Some improvements for this file output would be to:
1. put empty _sample_ elements in areas like Increase/DecreaseVolume for Amazon's syntax compatibility
2. keep the players.txt file in use to then populate element types-PLAYERS-values each time speechAssets is regenerated.
`  "types": [
    {
      "name": "PLAYERS",
      "values": [
        {
          "name": {
            "value": "Kitchen"
          }
        },
        {
          "name": {
            "value": "Master Bedroom"
          }
        }, ...`

I bring up the files to include in the zip because of muzak.js lines 14-18:
`var config = require('./config');
var albums = require('./album.js');
var artists = require('./artist.js');
var genres = require('./genre.js');
var info = { Album: albums, Artist: artists, Genre: genres };`

**Comment by GeoffAtHome** [comment]
I have moved the list of players into the config file as this should be the only file that needs to be customised. create-assets has been updated to support the latest changes to Amazon's skill builder beta. This now works with album, artist, genre and track.

note the "invocationName" in the default-assets.js file. This needs to be moved into the config file.

**Comment by GeoffAtHome** [comment]
It looks like all the look-up maybe able to be done by the service which will simplify lambda function. See https://developer.amazon.com/docs/custom-skills/define-synonyms-and-ids-for-slot-type-values-entity-resolution.html for details.

**Comment by GeoffAtHome** [comment]
At the moment this work so closing this issue. To improve will need to use entity-resolution. At this point I cannot figure how to get this working. Even the examples from Amazon do not work for me.
